apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  labels:
    app: benfa-yaml-test
  name: benfa-yaml-test
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: benfa-yaml-test:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: https://cousinea@bitbucket.org/tlcsitsumichedu/oscpdev.git
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: drupal7-cosign:latest
        namespace: openshift
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: KhoQ8tdTk5rHDmYBOOm-
    type: GitHub
  - generic:
      secret: cbM0U5E5vlyfet9Lojdu
    type: Generic
  - imageChange: {}
    type: ImageChange
  - type: ConfigChange
status:
  lastVersion: 0
