apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  labels:
    app: benfa-yaml-test
  name: benfa-yaml-test
spec:
  ports:
#  - name: 80-tcp
#    port: 80
#    protocol: TCP
#    targetPort: 80
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: 8443-tcp
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app: benfa-yaml-test
    deploymentconfig: benfa-yaml-test
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
